#!/usr/bin/env python
from argparse import ArgumentParser
from itertools import izip
from stevedore.extension import ExtensionManager
from sys import exit


if __name__ == '__main__':
    argument_parser = ArgumentParser()
    extension_manager = ExtensionManager(
        namespace='invisibleroads', invoke_on_load=True)
    extension_manager.map_method('configure', [argument_parser])
    arguments = argument_parser.parse_args()

    extension_by_name = {name: extension.obj.run for name, extension in izip(
        extension_manager.names(), extension_manager.extensions)}
    try:
        run = extension_by_name[arguments.command]
    except (AttributeError, KeyError):
        exit()
    run(arguments)
